### ISSUE TITLE
my python3 is at /usr/bin/python3 not /bin/python3

### ISSUE THREAD

**Issue by equwal** [Ajatt-Tools/transformers_ocr#8]
- The program crashes?
yes
- The program stopped working?
yes
- Have a feature request?
NEIN

**Environment**

1) OS name  [e.g. Parabola, Debian]
install gentoo 
2) OS version
recent
4) Log
```
.../Ajatt-Tools/transformers_ocr main>> transformers_ocr download
zsh: /usr/bin/transformers_ocr: bad interpreter: /bin/python3: no such file or directory
```
5) Screenshots, if applicable
https://ibb.co/G3T3HVv

**Describe the bug**
wrong PATH use

**To Reproduce**
1) no python at /bin
2) python at /usr/bin etc. for example
3) See error

Workaround: use `ln`.

**Comment by tatsumoto-ren** [comment]
you can change the shebang and set it to `/usr/bin/python3`. it should work then.
